---
- hosts: all
  tasks:
    - name: Copy file from local to remote
      win_copy: src=/etc/passwd dest=c:\1\
      notify:
        - restart iis
  handlers:
    - name: restart iis
      win_ping:
